AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS DMS Replication Instance
Parameters:
  StackName:
    Type: String
  DmsSubnetIds:
    Type: CommaDelimitedList
    Description: Dms Instance SubnetIds

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationinstance.html
  ReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      ReplicationInstanceIdentifier: !Ref StackName
      ReplicationInstanceClass: dms.t3.nano
      AllocatedStorage: 10
      MultiAZ: False
      AvailabilityZone: ap-northeast-1a
      PubliclyAccessible: False
      PreferredMaintenanceWindow: Tue:06:00-Tue:06:30
      AllowMajorVersionUpgrade: False
      AutoMinorVersionUpgrade: True
      ReplicationSubnetGroupIdentifier: !Ref ReplicationSubnetGroup

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationsubnetgroup.html
  ReplicationSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties:
      ReplicationSubnetGroupDescription: !Ref StackName
      SubnetIds: !Ref DmsSubnetIds
    DependsOn: DmsVpcRole

  # https://forums.aws.amazon.com/thread.jspa?messageID=921775
  DmsVpcRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dms-vpc-role
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - dms.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole

Outputs:
  ReplicationInstanceArn:
    Value: !Ref ReplicationInstance

