AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS DMS Migration tasks
Parameters:
  ReplicationInstanceArn:
    Type: String
  SourceEndpointArn:
    Type: String
  TargetEndpointArn:
    Type: String

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html
  # 2022-03-12: Currently, the only endpoint setting types that AWS CloudFormation supports are DynamoDBSettings, ElasticSearchSettings, and NeptuneSettings.

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationtask.html
  ReplicationTask:
    Type: AWS::DMS::ReplicationTask
    Properties:
      ReplicationTaskIdentifier: !Ref AWS::StackName
      MigrationType: cdc
      SourceEndpointArn: !Ref SourceEndpointArn
      TargetEndpointArn: !Ref TargetEndpointArn
      ReplicationInstanceArn: !Ref ReplicationInstanceArn
      # https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Tasks.CustomizingTasks.TaskSettings.html
      ReplicationTaskSettings: '{
        "TargetMetadata": {
          "TargetSchema": "",
          "LoadMaxFileSize": 0,
          "BatchApplyEnabled": false,
          "ParallelApplyBufferSize": 0,
          "ParallelApplyQueuesPerThread": 0,
          "ParallelApplyThreads": 0,
          "ParallelLoadBufferSize": 0,
          "ParallelLoadQueuesPerThread": 0,
          "ParallelLoadThreads": 0,
          "SupportLobs": true,
          "FullLobMode": false,
          "LobChunkSize": 0,
          "InlineLobMaxSize": 0,
          "LimitedSizeLobMode": true,
          "LobMaxSize": 32,
          "TaskRecoveryTableEnabled": false,
        },
        "ChangeProcessingTuning": {
          "MemoryLimitTotal": 1024,
          "MemoryKeepTime": 60,
          "StatementCacheSize": 50,
        },
        "ChangeProcessingDdlHandlingPolicy": {
          "HandleSourceTableDropped": true,
          "HandleSourceTableTruncated": true,
          "HandleSourceTableAltered": true,
        },
        "StreamBufferSettings": {
          "StreamBufferCount": 3,
          "CtrlStreamBufferSizeInMB": 5,
          "StreamBufferSizeInMB": 8,
        },
        "FailTaskWhenCleanTaskResourceFailed": false,
        "ErrorBehavior": {
          "DataErrorPolicy": "LOG_ERROR",
          "DataTruncationErrorPolicy": "LOG_ERROR",
          "DataErrorEscalationPolicy": "SUSPEND_TABLE",
          "DataErrorEscalationCount": 0,
          "TableErrorPolicy": "SUSPEND_TABLE",
          "TableErrorEscalationPolicy": "STOP_TASK",
          "TableErrorEscalationCount": 0,
          "RecoverableErrorCount": -1,
          "RecoverableErrorThrottling": true,
          "RecoverableErrorInterval": 5,
          "RecoverableErrorThrottlingMax": 1800,
          "RecoverableErrorStopRetryAfterThrottlingMax": true,
          "ApplyErrorDeletePolicy": "IGNORE_RECORD",
          "ApplyErrorInsertPolicy": "LOG_ERROR",
          "ApplyErrorUpdatePolicy": "LOG_ERROR",
          "ApplyErrorEscalationPolicy": "LOG_ERROR",
          "ApplyErrorEscalationCount": 0,
          "ApplyErrorFailOnTruncationDdl": false,
          "FailOnNoTablesCaptured": true,
          "FailOnTransactionConsistencyBreached": false,
          "FullLoadIgnoreConflicts": true,
        },
        }'
      # https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Tasks.CustomizingTasks.TableMapping.SelectionTransformation.Selections.html
      TableMappings: '{
        "rules": [{
          "rule-type": "selection",
          "rule-id": "1",
          "rule-name": "1",
          "object-locator": { "schema-name": "%", "table-name": "%" },
          "rule-action": "include"
        }]
        }'
