name: Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli
      - name: Deploy Lambda Resources
        run: |
          sam build -t templates/lambda/lambda.yaml
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name cdc-rds-bq-lambda \
            --s3-bucket ${{ secrets.AWS_SAM_S3_BUCKET }} \
            --s3-prefix cdc-rds-bq-lambda \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides GcpServiceAccountSecretsArn=\"${{ secrets.GCP_SERVICE_ACCOUNT_SECRETS_ARN }}\"
            --image-repository="load_parquet_to_bigquery"
